#!/usr/bin/env bash
set -e

# Default Variables
# ---
DEFAULT_USERNAME="casper"
DEFAULT_CONFIG_DIRECTORY="/etc/${DEFAULT_USERNAME}"
DEFAULT_DATA_DIRECTORY="/var/lib/${DEFAULT_USERNAME}"
DEFAULT_LOG_DIRECOTRY="/var/log/${DEFAULT_USERNAME}"

# User Creation
# ---
# Assure DEFAULT_USERNAME user exists
if id -u ${DEFAULT_USERNAME} >/dev/null 2>&1; then
    echo "User ${DEFAULT_USERNAME} already exists."
else
    adduser --no-create-home --group --system ${DEFAULT_USERNAME}
fi

CONFIG_SCRIPT="${DEFAULT_CONFIG_DIRECTORY}/config_from_example.sh"
# create config.toml from config-example.toml
if [[ -f ${CONFIG_SCRIPT} ]]; then
  $CONFIG_SCRIPT
else
  echo "${CONFIG_SCRIPT} not found."
  exit 1
fi

# run pull_genesis script to get latest files
PULL_GENESIS_SCRIPT="${DEFAULT_CONFIG_DIRECTORY}/pull_genesis.sh"
# create config.toml or config.toml.new from config-example.toml
if [[ -f ${PULL_GENESIS_SCRIPT} ]]; then
  $PULL_GENESIS_SCRIPT
else
  echo "${PULL_GENESIS_SCRIPT} not found."
  exit 1
fi

# Take ownership of directories and files installed
chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_DATA_DIRECTORY}
chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_CONFIG_DIRECTORY}
chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_LOG_DIRECOTRY}

# This is required for replacement to insert scripts for systemd by cargo-deb
#DEBHELPER#
