---
platform:
  os: linux
  arch: amd64

# Begin
clone:
  git-clone:
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
    image: "casperlabs/buildenv:latest"

# NOTE: Anchors are per document
# Anchor for default buildenv
__buildenv: &buildenv
  image: "casperlabs/buildenv:latest"
  environment:
    CARGO_HOME: ".cargo"

# Anchor for cache plugin
# Caching based on https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
__cache: &cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    mount:
      - ./.cargo/bin/
      - ./.cargo/registry/index/
      - ./.cargo/registry/cache/
      - ./.cargo/git/db/
      - ./.cargo/.crates.toml

kind: pipeline
name: cargo

steps:
- name: restore-cache
  <<: *cache
  settings:
    restore: true

- name: cargo-fmt
  <<: *buildenv
  commands:
  - rustup component add rustfmt
  - cargo fmt --all -- --check

- name: cargo-clippy
  <<: *buildenv
  environment:
    RUSTFLAGS: '-D warnings'
  commands:
  - make setup-rs
  - rustup component add clippy
  - cargo clippy --all-targets --all-features --workspace

- name: cargo-audit
  <<: *buildenv
  commands:
  - cargo install cargo-audit
  - cargo generate-lockfile
  - cargo audit

- name: cargo-test
  <<: *buildenv
  commands:
  - make setup
  - make test
  - make test-contracts

- name: rebuild-cache
  <<: *cache
  settings:
    rebuild: true
  when:
    branch:
    - master
    event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
  - master
  - trying
  - staging

---
# Anchor for default buildenv
__buildenv: &buildenv
  image: "casperlabs/buildenv:latest"
  environment:
    CARGO_HOME: ".cargo"

kind: pipeline
name: on-tag

steps:
- name: restore-cache-tag
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    mount:
      - ./.cargo/bin/
      - ./.cargo/registry/index/
      - ./.cargo/registry/cache/
      - ./.cargo/git/db/
      - ./.cargo/.crates.toml
    restore: true

- name: build-release-tag
  <<: *buildenv
  commands:
  - "cargo build --release"
  depends_on:
  - restore-cache-tag

- name: build-deb-tag
  <<: *buildenv
  commands:
    - "make deb"
  depends_on:
  - build-release-tag

- name: publish-github-tag
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    - md5
    files:
    - "./target/debian/*.deb"
    prerelease:
    - true
  depends_on:
  - build-deb-tag

- name: publish-crate-tag
  <<: *buildenv
  commands:
  - "echo TODO"
  depends_on:
  - build-release-tag

- name: publish-bintray-tag
  <<: *buildenv
  commands:
  - "echo TODO"
  depends_on:
  - build-deb-tag

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  ref:
  - refs/tags/v*

---
# Anchor for default buildenv
__buildenv: &buildenv
  image: "casperlabs/buildenv:latest"
  environment:
    CARGO_HOME: ".cargo"

kind: pipeline
name: bintray-tests

steps:
- name: restore-cache-tag
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    mount:
      - ./.cargo/bin/
      - ./.cargo/registry/index/
      - ./.cargo/registry/cache/
      - ./.cargo/git/db/
      - ./.cargo/.crates.toml
    restore: true

- name: cargo-fmt
  <<: *buildenv
  commands:
  - rustup component add rustfmt
  - cargo fmt --all -- --check

- name: cargo-clippy
  <<: *buildenv
  environment:
    RUSTFLAGS: '-D warnings'
  commands:
  - make setup-rs
  - rustup component add clippy
  - cargo clippy --all-targets --all-features --workspace

- name: cargo-audit
  <<: *buildenv
  commands:
  - cargo install cargo-audit
  - cargo generate-lockfile
  - cargo audit
  depends_on:
  - cargo-clippy

- name: build-deb-tag
  <<: *buildenv
  commands:
    - "make setup-rs"
    - "make deb"
  depends_on:
  - cargo-audit

- name: publish-bintray-tag
  <<: *buildenv
  commands:
  - "./upload.sh --repo-name casper-debian-tests --package-name casper-node"
  environment:
    BINTRAY_API_KEY:
      from_secret: cl_bintray_api_key
    CL_VAULT_TOKEN:
      from_secret: vault_token
    CL_VAULT_HOST:
      from_secret: vault_host
  depends_on:
  - build-deb-tag

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
  - OP-1540
  - OP-1540-new
  event:
  - push

---
kind: pipeline
name: failed-build-alert

clone:
  disable: true

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    template:
    - |
      casper-node build status: *{{ uppercasefirst build.status }}*
      Author: {{ build.author }}
      Drone Build: <{{ build.link }}|#{{ build.number }}>
      Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
  - failure
  branch:
  - master
  - trying
  - staging

depends_on:
- cargo
