[package]
name = "vm2-trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
casper-macros = { path = "../../../macros" }
casper-sdk = { path = "../../../sdk" }
base16 = "0.2.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_json = "1"
