[package]
name = "vm2-test-contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-macros = { path = "../../../macros" }
casper-sdk = { path = "../../../sdk" }

borsh = "1.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_json = "1"
