[package]
name = "create-test-node-03"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2021"

[[bin]]
name = "create_test_node_03"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
create-test-node-shared = { path = "../create-test-node-shared" }
