mod finalized_transaction_v1_approvals;
mod transaction_v1_hash_with_approvals;

pub(crate) use finalized_transaction_v1_approvals::FinalizedTransactionV1Approvals;
pub(crate) use transaction_v1_hash_with_approvals::TransactionV1HashWithApprovals;
