[package]
name = "do-nothing-revert-stored"
version = "0.1.0"
authors = ["Jakub Zajkowski <jakub@casper.network>"]
edition = "2021"

[[bin]]
name = "do_nothing_revert_stored"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
