use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
    sync::Arc,
};

use bytes::Bytes;
use casper_execution_engine::engine_state::{EngineConfig, ExecutionEngineV1};
use casper_executor_wasm_interface::executor::{
    ExecuteRequest, ExecuteRequestBuilder, ExecuteWithProviderError, ExecuteWithProviderResult,
};
use casper_storage::{
    data_access_layer::{GenesisRequest, GenesisResult},
    global_state::{
        self,
        state::{lmdb::LmdbGlobalState, CommitProvider},
    },
    system::runtime_native::Id,
    AddressGenerator, RuntimeNativeConfig,
};
use casper_types::{
    account::AccountHash, AuctionCosts, BlockHash, Chainspec, ChainspecRegistry, Digest,
    FeeHandling, GenesisAccount, GenesisConfig, GenesisValidator, HostFFIFunctionCost,
    HostFFIFunctionCosts, Key, MessageLimits, MintCosts, Motes, Phase, ProtocolVersion, PublicKey,
    SecretKey, StorageCosts, SystemConfig, Timestamp, TransactionHash, TransactionV1Hash,
    WasmConfig, WasmV2Config, DEFAULT_BASELINE_MOTES_AMOUNT, DEFAULT_WASM_MAX_MEMORY, U512,
};
use num_rational::Ratio;

use crate::{
    chainspec_config::ChainspecConfig,
    install::{
        InstallContractError, InstallContractRequest, InstallContractRequestBuilder,
        InstallContractResult,
    },
    ExecutorConfigBuilder, ExecutorKind, ExecutorV2,
};
use casper_storage::system::runtime_native::{Config, TransferConfig};
use casper_types::system::auction::DelegationRate;
use once_cell::sync::Lazy;
use parking_lot::RwLock;
use tempfile::TempDir;

pub static DEFAULT_ACCOUNT_SECRET_KEY: Lazy<SecretKey> =
    Lazy::new(|| SecretKey::ed25519_from_bytes([199; SecretKey::ED25519_LENGTH]).unwrap());
pub static DEFAULT_ACCOUNT_PUBLIC_KEY: Lazy<PublicKey> =
    Lazy::new(|| PublicKey::from(&*DEFAULT_ACCOUNT_SECRET_KEY));
pub static DEFAULT_ACCOUNT_HASH: Lazy<AccountHash> =
    Lazy::new(|| DEFAULT_ACCOUNT_PUBLIC_KEY.to_account_hash());

pub static DEFAULT_STABLE_VALIDATOR_PUBLIC_KEY: Lazy<PublicKey> =
    Lazy::new(|| casper_types::ed25519_imputed(&[1; 32]));
pub static DEFAULT_STABLE_DELEGATOR_PUBLIC_KEY: Lazy<PublicKey> =
    Lazy::new(|| casper_types::ed25519_imputed(&[255; 32]));

pub const TOKEN: u64 = 10u64.pow(9);

pub static RUST_WORKSPACE_PATH: Lazy<PathBuf> = Lazy::new(|| {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("CARGO_MANIFEST_DIR should have parent");
    assert!(
        path.exists(),
        "Workspace path {} does not exists",
        path.display()
    );
    path.to_path_buf()
});

pub static RUST_WORKSPACE_WASM_PATH: Lazy<PathBuf> = Lazy::new(|| {
    let path = RUST_WORKSPACE_PATH
        .join("target")
        .join("wasm32-unknown-unknown")
        .join("release");
    assert!(
        path.exists() || RUST_TOOL_WASM_PATH.exists(),
        "Rust Wasm path {} does not exists",
        path.display()
    );
    path
});

// The location of compiled Wasm files if running from within the 'tests' crate generated by the
// cargo_casper tool, i.e. 'wasm/'.
pub static RUST_TOOL_WASM_PATH: Lazy<PathBuf> = Lazy::new(|| {
    env::current_dir()
        .expect("should get current working dir")
        .join("wasm")
});

#[track_caller]
pub fn read_wasm<P: AsRef<Path>>(filename: P) -> Bytes {
    let paths = vec![
        RUST_WORKSPACE_WASM_PATH.clone(),
        RUST_TOOL_WASM_PATH.clone(),
    ];

    for path in &paths {
        let wasm_path = path.join(&filename);
        match fs::read(wasm_path) {
            Ok(bytes) => return Bytes::from(bytes),
            Err(err) => {
                if err.kind() == std::io::ErrorKind::NotFound {
                    continue;
                } else {
                    panic!(
                        "Failed to read Wasm file at {}: {}",
                        filename.as_ref().display(),
                        err
                    );
                }
            }
        }
    }

    panic!(
        "Failed to find Wasm file at {} in any of the paths: {:?}",
        filename.as_ref().display(),
        paths
    );
}

pub const TRANSACTION_HASH_BYTES: [u8; 32] = [55; 32];
pub const TRANSACTION_HASH: TransactionHash =
    TransactionHash::V1(TransactionV1Hash::from_raw(TRANSACTION_HASH_BYTES));
pub const DEFAULT_GAS_LIMIT: u64 = 1_000_000 * TOKEN;
pub const DEFAULT_CHAIN_NAME: &str = "casper-test";

pub fn make_address_generator() -> Arc<RwLock<AddressGenerator>> {
    let id = Id::Transaction(TRANSACTION_HASH);
    Arc::new(RwLock::new(AddressGenerator::new(
        &id.seed(),
        Phase::Session,
    )))
}

pub fn base_execute_builder(chainspec_config: &ChainspecConfig) -> ExecuteRequestBuilder {
    let chainspec = Chainspec::default();
    let runtime_native_config = RuntimeNativeConfig::from_chainspec(&chainspec);
    ExecuteRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(1000)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::hash(b"state"))
        .with_block_height(1)
        .with_runtime_native_config(make_runtime_config(chainspec_config))
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block1")))
        .with_runtime_native_config(runtime_native_config)
        .with_authorization_keys(BTreeSet::from_iter([*DEFAULT_ACCOUNT_HASH]))
}

pub fn make_runtime_config(chainspec_config: &ChainspecConfig) -> RuntimeNativeConfig {
    let protocol_version = ProtocolVersion::V2_0_0;
    let transfer_config = TransferConfig::Unadministered;
    let fee_handling = chainspec_config.core_config.fee_handling;
    let refund_handling = chainspec_config.core_config.refund_handling;
    let vesting_schedule_period_millis = chainspec_config
        .core_config
        .vesting_schedule_period
        .millis();
    let allow_auction_bids = chainspec_config.core_config.allow_auction_bids;
    let compute_rewards = chainspec_config.core_config.compute_rewards;
    let max_delegators_per_validator = chainspec_config.core_config.max_delegators_per_validator;
    let minimum_bid_amount = chainspec_config.core_config.minimum_bid_amount;
    let minimum_delegation_amount = chainspec_config.core_config.minimum_delegation_amount;
    let maximum_delegation_amount = chainspec_config.core_config.maximum_delegation_amount;
    let balance_hold_interval = chainspec_config.core_config.gas_hold_interval.millis();
    let include_credits = chainspec_config.core_config.fee_handling == FeeHandling::NoFee;
    let credit_cap = Ratio::new_raw(
        U512::from(*chainspec_config.core_config.validator_credit_cap.numer()),
        U512::from(*chainspec_config.core_config.validator_credit_cap.denom()),
    );
    let addressable_entity_enabled = chainspec_config.core_config.addressable_entity_enabled;
    let native_transfer_cost = chainspec_config.system_costs_config.mint_costs().transfer;
    Config::new(
        protocol_version,
        transfer_config,
        fee_handling,
        refund_handling,
        vesting_schedule_period_millis,
        allow_auction_bids,
        compute_rewards,
        max_delegators_per_validator,
        minimum_bid_amount,
        minimum_delegation_amount,
        maximum_delegation_amount,
        balance_hold_interval,
        include_credits,
        credit_cap,
        addressable_entity_enabled,
        native_transfer_cost,
    )
}

pub fn base_install_request_builder(
    chainspec_config: &ChainspecConfig,
) -> InstallContractRequestBuilder {
    let chainspec = Chainspec::default();
    let runtime_native_config = RuntimeNativeConfig::from_chainspec(&chainspec);
    InstallContractRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::hash(b"state"))
        .with_block_height(1)
        .with_runtime_native_config(make_runtime_config(chainspec_config))
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block1")))
        .with_runtime_native_config(runtime_native_config)
        .with_authorization_keys(BTreeSet::from_iter([*DEFAULT_ACCOUNT_HASH]))
}

pub fn make_executor(chainspec_config: &ChainspecConfig) -> ExecutorV2 {
    let storage_costs = chainspec_config.storage_costs;
    let mint_costs = chainspec_config.system_costs_config.mint_costs().clone();
    let auction_costs = chainspec_config.system_costs_config.auction_costs().clone();
    let v1_config = EngineConfig::from(chainspec_config.clone());
    let execution_engine_v1 = ExecutionEngineV1::new(v1_config);
    let wasm_v2_config = *chainspec_config.wasm_config.v2();
    let memory_limit = wasm_v2_config.max_memory();
    let message_limits = chainspec_config.wasm_config.messages_limits();
    let executor_config = ExecutorConfigBuilder::default()
        .with_memory_limit(memory_limit)
        .with_executor_kind(ExecutorKind::Compiled)
        .with_wasm_config(wasm_v2_config)
        .with_storage_costs(storage_costs)
        .with_mint_costs(mint_costs)
        .with_auction_costs(auction_costs)
        .with_baseline_motes_amount(chainspec_config.core_config.baseline_motes_amount)
        .with_message_limits(message_limits)
        .build()
        .expect("Should build");
    ExecutorV2::new(executor_config, execution_engine_v1)
}

pub fn make_global_state_with_genesis() -> (LmdbGlobalState, Digest, TempDir) {
    let acct_1 = GenesisAccount::Account {
        public_key: DEFAULT_ACCOUNT_PUBLIC_KEY.clone(),
        balance: Motes::new(U512::from(100 * TOKEN)),
        validator: None,
    };

    let acct_2 = GenesisAccount::Account {
        public_key: DEFAULT_STABLE_VALIDATOR_PUBLIC_KEY.clone(),
        balance: Motes::new(U512::from(200_000_000 * TOKEN)),
        validator: Some(GenesisValidator::new(
            Motes::new(U512::from(100_000_000 * TOKEN)),
            DelegationRate::MIN,
        )),
    };

    let acct_3 = GenesisAccount::Delegator {
        validator_public_key: DEFAULT_STABLE_VALIDATOR_PUBLIC_KEY.clone(),
        delegator_public_key: DEFAULT_STABLE_DELEGATOR_PUBLIC_KEY.clone(),
        balance: Motes::new(U512::from(100 * TOKEN)),
        delegated_amount: Motes::new(U512::from(100 * TOKEN)),
    };

    let default_accounts = vec![acct_1, acct_2, acct_3];

    let (global_state, _state_root_hash, _tempdir) =
        global_state::state::lmdb::make_temporary_global_state([]);

    let genesis_config = GenesisConfig::new(
        default_accounts,
        WasmConfig::default(),
        SystemConfig::default(),
        10,
        10,
        0,
        Default::default(),
        14,
        Timestamp::now().millis(),
        casper_types::HoldBalanceHandling::Accrued,
        0,
        false,
        StorageCosts::default(),
    );
    let genesis_request: GenesisRequest = GenesisRequest::new(
        Digest::hash("foo"),
        ProtocolVersion::V2_0_0,
        genesis_config,
        ChainspecRegistry::new_with_genesis(b"", b""),
    );
    match global_state.genesis(genesis_request) {
        GenesisResult::Failure(failure) => panic!("Failed to run genesis: {:?}", failure),
        GenesisResult::Fatal(fatal) => panic!("Fatal error while running genesis: {}", fatal),
        GenesisResult::Success {
            post_state_hash,
            effects: _,
        } => (global_state, post_state_hash, _tempdir),
    }
}

pub fn run_create_contract(
    executor: &mut ExecutorV2,
    global_state: &LmdbGlobalState,
    pre_state_hash: Digest,
    install_contract_request: InstallContractRequest,
) -> InstallContractResult {
    executor
        .install_contract(pre_state_hash, global_state, install_contract_request)
        .expect("run_create_contract should succeed")
}

pub fn expect_successful_execution(
    executor: &mut ExecutorV2,
    global_state: &LmdbGlobalState,
    pre_state_hash: Digest,
    execute_request: ExecuteRequest,
) -> ExecuteWithProviderResult {
    match run_wasm_session(executor, global_state, pre_state_hash, execute_request) {
        Ok(result) => {
            if let Some(host_error) = result.host_error {
                panic!("Host error: {host_error:?}")
            }
            result
        }
        Err(err) => {
            panic!("Provider error: {err:?}")
        }
    }
}

pub fn run_wasm_session(
    executor: &mut ExecutorV2,
    global_state: &LmdbGlobalState,
    pre_state_hash: Digest,
    execute_request: ExecuteRequest,
) -> Result<ExecuteWithProviderResult, ExecuteWithProviderError> {
    executor.execute_with_provider(pre_state_hash, global_state, execute_request)
}

pub fn call_dummy_host_fn_by_name(
    chainspec_config: &ChainspecConfig,
    host_function_name: &str,
    gas_limit: u64,
) -> Result<InstallContractResult, InstallContractError> {
    let executor = {
        let execution_engine_v1 = ExecutionEngineV1::default();
        let default_wasm_config = WasmV2Config::default();
        let wasm_config = WasmV2Config::new(
            default_wasm_config.max_memory(),
            default_wasm_config.opcode_costs(),
            HostFFIFunctionCosts {
                read: HostFFIFunctionCost::fixed(1),
                write: HostFFIFunctionCost::fixed(1),
                remove: HostFFIFunctionCost::fixed(1),
                copy_input: HostFFIFunctionCost::fixed(1),
                ret: HostFFIFunctionCost::fixed(1),
                create: HostFFIFunctionCost::fixed(1),
                transfer: HostFFIFunctionCost::fixed(1),
                env_balance: HostFFIFunctionCost::fixed(1),
                upgrade: HostFFIFunctionCost::fixed(1),
                call: HostFFIFunctionCost::fixed(1),
                print: HostFFIFunctionCost::fixed(1),
                emit: HostFFIFunctionCost::fixed(1),
                env_info: HostFFIFunctionCost::fixed(1),
                generic_hash: HostFFIFunctionCost::fixed(1),
                recover_secp256k1: HostFFIFunctionCost::fixed(1),
                alt_bn128_add: HostFFIFunctionCost::fixed(1),
                alt_bn128_mul: HostFFIFunctionCost::fixed(1),
                alt_bn128_pairing: HostFFIFunctionCost::fixed(1),
            },
        );
        let executor_config = ExecutorConfigBuilder::default()
            .with_memory_limit(DEFAULT_WASM_MAX_MEMORY)
            .with_executor_kind(ExecutorKind::Compiled)
            .with_wasm_config(wasm_config)
            .with_storage_costs(StorageCosts::default())
            .with_mint_costs(MintCosts::default())
            .with_auction_costs(AuctionCosts::default())
            .with_baseline_motes_amount(DEFAULT_BASELINE_MOTES_AMOUNT)
            .with_message_limits(MessageLimits::default())
            .build()
            .expect("Should build");
        ExecutorV2::new(executor_config, execution_engine_v1)
    };

    let (global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let input_data = borsh::to_vec(&(host_function_name.to_owned(),))
        .map(Bytes::from)
        .expect("Expected borsh to work");

    let create_request = base_install_request_builder(chainspec_config)
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_gas_limit(gas_limit)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_host.wasm"))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_input(input_data)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");

    executor.install_contract(state_root_hash, &global_state, create_request)
}
