use std::{
    env,
    fs::{self, File},
    path::{Path, PathBuf},
    sync::Arc,
};

use bytes::Bytes;
use casper_execution_engine::engine_state::ExecutionEngineV1;
use casper_executor_wasm::{
    install::{
        InstallContractError, InstallContractRequest, InstallContractRequestBuilder,
        InstallContractResult,
    },
    ExecutorConfigBuilder, ExecutorKind, ExecutorV2,
};
use casper_executor_wasm_common::error::CallError;
use casper_executor_wasm_interface::executor::{
    ExecuteError, ExecuteRequest, ExecuteRequestBuilder, ExecuteWithProviderError,
    ExecuteWithProviderResult, ExecutionKind,
};
use casper_storage::{
    data_access_layer::{
        prefixed_values::{PrefixedValuesRequest, PrefixedValuesResult},
        GenesisRequest, GenesisResult, MessageTopicsRequest, MessageTopicsResult, QueryRequest,
        QueryResult,
    },
    global_state::{
        self,
        state::{lmdb::LmdbGlobalState, CommitProvider, StateProvider},
        transaction_source::lmdb::LmdbEnvironment,
        trie_store::lmdb::LmdbTrieStore,
    },
    system::runtime_native::Id,
    AddressGenerator, KeyPrefix,
};
use casper_types::{
    account::AccountHash,
    addressable_entity::DEFAULT_ENTRY_POINT_NAME,
    execution::{RetValue, TransformKindV2, TransformV2},
    BlockHash, ChainspecRegistry, Digest, EntityAddr, GenesisAccount, GenesisConfig,
    HostFunctionCostsV2, HostFunctionV2, Key, MessageLimits, Motes, Phase, ProtocolVersion,
    PublicKey, SecretKey, StorageCosts, StoredValue, SystemConfig, Timestamp, TransactionHash,
    TransactionV1Hash, WasmConfig, WasmV2Config, U512,
};
use fs_extra::dir;
use itertools::Itertools;
use once_cell::sync::Lazy;
use parking_lot::RwLock;
use tempfile::TempDir;

static DEFAULT_ACCOUNT_SECRET_KEY: Lazy<SecretKey> =
    Lazy::new(|| SecretKey::ed25519_from_bytes([199; SecretKey::ED25519_LENGTH]).unwrap());
static DEFAULT_ACCOUNT_PUBLIC_KEY: Lazy<casper_types::PublicKey> =
    Lazy::new(|| PublicKey::from(&*DEFAULT_ACCOUNT_SECRET_KEY));
static DEFAULT_ACCOUNT_HASH: Lazy<AccountHash> =
    Lazy::new(|| DEFAULT_ACCOUNT_PUBLIC_KEY.to_account_hash());

const CSPR: u64 = 10u64.pow(9);

static RUST_WORKSPACE_PATH: Lazy<PathBuf> = Lazy::new(|| {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("CARGO_MANIFEST_DIR should have parent");
    assert!(
        path.exists(),
        "Workspace path {} does not exists",
        path.display()
    );
    path.to_path_buf()
});

static RUST_WORKSPACE_WASM_PATH: Lazy<PathBuf> = Lazy::new(|| {
    let path = RUST_WORKSPACE_PATH
        .join("target")
        .join("wasm32v1-none")
        .join("release");
    assert!(
        path.exists() || RUST_TOOL_WASM_PATH.exists(),
        "Rust Wasm path {} does not exists",
        path.display()
    );
    path
});
// The location of compiled Wasm files if running from within the 'tests' crate generated by the
// cargo_casper tool, i.e. 'wasm/'.
static RUST_TOOL_WASM_PATH: Lazy<PathBuf> = Lazy::new(|| {
    env::current_dir()
        .expect("should get current working dir")
        .join("wasm")
});

#[track_caller]
fn read_wasm<P: AsRef<Path>>(filename: P) -> Bytes {
    let paths = vec![
        RUST_WORKSPACE_WASM_PATH.clone(),
        RUST_TOOL_WASM_PATH.clone(),
    ];

    for path in &paths {
        let wasm_path = path.join(&filename);
        match fs::read(wasm_path) {
            Ok(bytes) => return Bytes::from(bytes),
            Err(err) => {
                if err.kind() == std::io::ErrorKind::NotFound {
                    continue;
                } else {
                    panic!(
                        "Failed to read Wasm file at {}: {}",
                        filename.as_ref().display(),
                        err
                    );
                }
            }
        }
    }

    panic!(
        "Failed to find Wasm file at {} in any of the paths: {:?}",
        filename.as_ref().display(),
        paths
    );
}

const TRANSACTION_HASH_BYTES: [u8; 32] = [55; 32];
const TRANSACTION_HASH: TransactionHash =
    TransactionHash::V1(TransactionV1Hash::from_raw(TRANSACTION_HASH_BYTES));
const DEFAULT_GAS_LIMIT: u64 = 1_000_000 * CSPR;
const DEFAULT_CHAIN_NAME: &str = "casper-test";

// TODO: This is a temporary value, it should be set in the config. Default value from V1 engine
// does not apply to V2 engine due to different cost structure. Rather than hardcoding it here, we
// should probably reflect gas costs in a dynamic costs in host function charge. Proper value is
// pending calculation.
const DEFAULT_GAS_PER_BYTE_COST: u32 = 1_117_587;

fn make_address_generator() -> Arc<RwLock<AddressGenerator>> {
    let id = Id::Transaction(TRANSACTION_HASH);
    Arc::new(RwLock::new(AddressGenerator::new(
        &id.seed(),
        Phase::Session,
    )))
}

fn base_execute_builder() -> ExecuteRequestBuilder {
    ExecuteRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(1000)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::hash(b"state"))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block1")))
}

fn base_install_request_builder() -> InstallContractRequestBuilder {
    InstallContractRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::hash(b"state"))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block1")))
}

#[test]
fn harness() {
    let mut executor = make_executor();

    let (mut global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let flipper_address;

    state_root_hash = {
        let input_data = borsh::to_vec(&("Foo Token".to_string(),))
            .map(Bytes::from)
            .unwrap();

        let install_request = base_install_request_builder()
            .with_wasm_bytes(read_wasm("vm2_cep18.wasm"))
            .with_shared_address_generator(Arc::clone(&address_generator))
            .with_transferred_value(0)
            .with_entry_point("new".to_string())
            .with_input(input_data)
            .build()
            .expect("should build");

        let create_result = run_create_contract(
            &mut executor,
            &mut global_state,
            state_root_hash,
            install_request,
        );

        flipper_address = *create_result.smart_contract_addr();

        global_state
            .commit_effects(state_root_hash, create_result.effects().clone())
            .expect("Should commit")
    };

    let execute_request = ExecuteRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(1000)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_target(ExecutionKind::SessionBytes(read_wasm("vm2-harness.wasm")))
        .with_serialized_input((flipper_address,))
        .with_shared_address_generator(address_generator)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(state_root_hash)
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"bl0ck")))
        .build()
        .expect("should build");

    run_wasm_session(
        &mut executor,
        &mut global_state,
        state_root_hash,
        execute_request,
    );
}

pub(crate) fn make_executor() -> ExecutorV2 {
    let storage_costs = StorageCosts::new(DEFAULT_GAS_PER_BYTE_COST);
    let execution_engine_v1 = ExecutionEngineV1::default();
    let executor_config = ExecutorConfigBuilder::default()
        .with_memory_limit(17)
        .with_executor_kind(ExecutorKind::Compiled)
        .with_wasm_config(WasmV2Config::default())
        .with_storage_costs(storage_costs)
        .with_message_limits(MessageLimits::default())
        .build()
        .expect("Should build");
    ExecutorV2::new(executor_config, Arc::new(execution_engine_v1))
}

#[test]

fn cep18() {
    let mut executor = make_executor();

    let (mut global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let input_data = borsh::to_vec(&("Foo Token".to_string(),))
        .map(Bytes::from)
        .unwrap();

    let block_time_1 = Timestamp::now().into();

    let create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_cep18.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_input(input_data)
        .with_block_time(block_time_1)
        .with_state_hash(Digest::from_raw([0; 32])) // TODO: Carry on state root hash
        .with_block_height(1) // TODO: Carry on block height
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32]))) // TODO: Carry on parent block hash
        .build()
        .expect("should build");

    let create_result = run_create_contract(
        &mut executor,
        &mut global_state,
        state_root_hash,
        create_request,
    );

    dbg!(create_result.gas_usage().gas_spent());

    let contract_hash = EntityAddr::SmartContract(*create_result.smart_contract_addr());

    state_root_hash = global_state
        .commit_effects(state_root_hash, create_result.effects().clone())
        .expect("Should commit");

    let msgs = global_state.prefixed_values(PrefixedValuesRequest::new(
        state_root_hash,
        KeyPrefix::MessageEntriesByEntity(contract_hash),
    ));
    let PrefixedValuesResult::Success {
        key_prefix: _,
        values,
    } = msgs
    else {
        panic!("Expected success")
    };

    {
        let mut topics_1 = values
            .iter()
            .filter_map(|stored_value| stored_value.as_message_topic_summary())
            .collect_vec();
        topics_1
            .sort_by_key(|topic| (topic.topic_name(), topic.blocktime(), topic.message_count()));

        assert_eq!(topics_1[0].topic_name(), "Transfer");
        assert_eq!(topics_1[0].message_count(), 1);
        assert_eq!(topics_1[0].blocktime(), block_time_1);
    }

    let block_time_2 = (block_time_1.value() + 1).into();
    assert_ne!(block_time_1, block_time_2);

    let execute_request = ExecuteRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(1000)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_target(ExecutionKind::SessionBytes(read_wasm(
            "vm2_cep18_caller.wasm",
        )))
        .with_serialized_input((create_result.smart_contract_addr(),))
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(block_time_2)
        .with_state_hash(Digest::from_raw([0; 32])) // TODO: Carry on state root hash
        .with_block_height(2) // TODO: Carry on block height
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32]))) // TODO: Carry on parent block hash
        .build()
        .expect("should build");

    let result_2 = run_wasm_session(
        &mut executor,
        &mut global_state,
        state_root_hash,
        execute_request,
    );
    dbg!(result_2.gas_usage().gas_spent());

    state_root_hash = global_state
        .commit_effects(state_root_hash, result_2.effects().clone())
        .expect("Should commit");

    let MessageTopicsResult::Success { message_topics } =
        global_state.message_topics(MessageTopicsRequest::new(state_root_hash, contract_hash))
    else {
        panic!("Expected success")
    };

    assert!(matches!(message_topics.get("Transfer"), Some(_)));
    assert_ne!(
        message_topics.get("Mint"),
        message_topics.get("Transfer"),
        "Mint and Transfer topics should have different hashes"
    );

    {
        let msgs = global_state.prefixed_values(PrefixedValuesRequest::new(
            state_root_hash,
            KeyPrefix::MessageEntriesByEntity(contract_hash),
        ));
        let PrefixedValuesResult::Success {
            key_prefix: _,
            values,
        } = msgs
        else {
            panic!("Expected success")
        };

        let mut topics_2 = values
            .iter()
            .filter_map(|stored_value| stored_value.as_message_topic_summary())
            .collect_vec();
        topics_2
            .sort_by_key(|topic| (topic.topic_name(), topic.blocktime(), topic.message_count()));

        assert_eq!(topics_2.len(), 1);
        assert_eq!(topics_2[0].topic_name(), "Transfer");
        assert_eq!(topics_2[0].message_count(), 2);
        assert_eq!(topics_2[0].blocktime(), block_time_2); // NOTE: Session called mint; the topic
                                                           // summary blocktime is refreshed
    }

    let mut messages = result_2.messages().iter().collect_vec();
    messages.sort_by_key(|message| {
        (
            message.topic_name(),
            message.topic_index(),
            message.block_index(),
        )
    });
    assert_eq!(messages.len(), 2);
    assert_eq!(messages[0].topic_name(), "Transfer");
    assert_eq!(messages[0].topic_index(), 0);
    assert_eq!(messages[0].block_index(), 0);

    assert_eq!(messages[1].topic_name(), "Transfer");
    assert_eq!(messages[1].topic_index(), 1);
    assert_eq!(messages[1].block_index(), 1);
}

fn make_global_state_with_genesis() -> (LmdbGlobalState, Digest, TempDir) {
    let default_accounts = vec![GenesisAccount::Account {
        public_key: DEFAULT_ACCOUNT_PUBLIC_KEY.clone(),
        balance: Motes::new(U512::from(100 * CSPR)),
        validator: None,
    }];

    let (global_state, _state_root_hash, _tempdir) =
        global_state::state::lmdb::make_temporary_global_state([]);

    let genesis_config = GenesisConfig::new(
        default_accounts,
        casper_types::EvmConfig::default(),
        WasmConfig::default(),
        SystemConfig::default(),
        10,
        10,
        0,
        Default::default(),
        14,
        Timestamp::now().millis(),
        casper_types::HoldBalanceHandling::Accrued,
        0,
        true,
        None,
        StorageCosts::default(),
        0u8,
    );
    let genesis_request: GenesisRequest = GenesisRequest::new(
        Digest::hash("foo"),
        ProtocolVersion::V2_0_0,
        genesis_config,
        ChainspecRegistry::new_with_genesis(b"", b""),
    );
    match global_state.genesis(genesis_request) {
        GenesisResult::Failure(failure) => panic!("Failed to run genesis: {:?}", failure),
        GenesisResult::Fatal(fatal) => panic!("Fatal error while running genesis: {}", fatal),
        GenesisResult::Success {
            post_state_hash,
            effects: _,
        } => (global_state, post_state_hash, _tempdir),
    }
}

#[test]
fn traits() {
    let mut executor = make_executor();
    let (mut global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let execute_request = base_execute_builder()
        .with_target(ExecutionKind::SessionBytes(read_wasm("vm2_trait.wasm")))
        .with_serialized_input(())
        .with_shared_address_generator(make_address_generator())
        .build()
        .expect("should build");

    run_wasm_session(
        &mut executor,
        &mut global_state,
        state_root_hash,
        execute_request,
    );
}

#[test]
fn upgradable() {
    let mut executor = make_executor();

    let (mut global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let upgradable_address;

    state_root_hash = {
        let input_data = borsh::to_vec(&(0u8,)).map(Bytes::from).unwrap();

        let create_request = base_install_request_builder()
            .with_wasm_bytes(read_wasm("vm2_upgradable.wasm"))
            .with_shared_address_generator(Arc::clone(&address_generator))
            .with_gas_limit(DEFAULT_GAS_LIMIT)
            .with_transferred_value(0)
            .with_entry_point("new".to_string())
            .with_input(input_data)
            .build()
            .expect("should build");

        let create_result = run_create_contract(
            &mut executor,
            &mut global_state,
            state_root_hash,
            create_request,
        );

        upgradable_address = *create_result.smart_contract_addr();

        global_state
            .commit_effects(state_root_hash, create_result.effects().clone())
            .expect("Should commit")
    };

    let version_before_upgrade = {
        let execute_request = base_execute_builder()
            .with_target(ExecutionKind::Stored {
                address: upgradable_address,
                entry_point: "version".to_string(),
            })
            .with_input(Bytes::new())
            .with_gas_limit(DEFAULT_GAS_LIMIT)
            .with_transferred_value(0)
            .with_shared_address_generator(Arc::clone(&address_generator))
            .build()
            .expect("should build");
        let res = run_wasm_session(
            &mut executor,
            &mut global_state,
            state_root_hash,
            execute_request,
        );
        let output = res.output().expect("should have output");
        let version: String = borsh::from_slice(output).expect("should deserialize");
        version
    };
    assert_eq!(version_before_upgrade, "v1");

    {
        // Increment the value
        let execute_request = base_execute_builder()
            .with_target(ExecutionKind::Stored {
                address: upgradable_address,
                entry_point: "increment".to_string(),
            })
            .with_input(Bytes::new())
            .with_gas_limit(DEFAULT_GAS_LIMIT)
            .with_transferred_value(0)
            .with_shared_address_generator(Arc::clone(&address_generator))
            .build()
            .expect("should build");
        let res = run_wasm_session(
            &mut executor,
            &mut global_state,
            state_root_hash,
            execute_request,
        );
        state_root_hash = global_state
            .commit_effects(state_root_hash, res.effects().clone())
            .expect("Should commit");
    };

    let binding = read_wasm("vm2_upgradable_v2.wasm");
    let new_code = binding.as_ref();

    let execute_request = base_execute_builder()
        .with_transferred_value(0)
        .with_target(ExecutionKind::Stored {
            address: upgradable_address,
            entry_point: "perform_upgrade".to_string(),
        })
        .with_gas_limit(DEFAULT_GAS_LIMIT * 10)
        .with_serialized_input((new_code,))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .build()
        .expect("should build");
    let res = run_wasm_session(
        &mut executor,
        &mut global_state,
        state_root_hash,
        execute_request,
    );
    state_root_hash = global_state
        .commit_effects(state_root_hash, res.effects().clone())
        .expect("Should commit");

    let version_after_upgrade = {
        let execute_request = base_execute_builder()
            .with_target(ExecutionKind::Stored {
                address: upgradable_address,
                entry_point: "version".to_string(),
            })
            .with_input(Bytes::new())
            .with_gas_limit(DEFAULT_GAS_LIMIT)
            .with_transferred_value(0)
            .with_shared_address_generator(Arc::clone(&address_generator))
            .build()
            .expect("should build");
        let res = run_wasm_session(
            &mut executor,
            &mut global_state,
            state_root_hash,
            execute_request,
        );
        let output = res.output().expect("should have output");
        let version: String = borsh::from_slice(output).expect("should deserialize");
        version
    };
    assert_eq!(version_after_upgrade, "v2");

    {
        // Increment the value
        let execute_request = base_execute_builder()
            .with_target(ExecutionKind::Stored {
                address: upgradable_address,
                entry_point: "increment_by".to_string(),
            })
            .with_serialized_input((10u64,))
            .with_gas_limit(DEFAULT_GAS_LIMIT)
            .with_transferred_value(0)
            .with_shared_address_generator(Arc::clone(&address_generator))
            .build()
            .expect("should build");
        let res = run_wasm_session(
            &mut executor,
            &mut global_state,
            state_root_hash,
            execute_request,
        );
        state_root_hash = global_state
            .commit_effects(state_root_hash, res.effects().clone())
            .expect("Should commit");
    };

    let _ = state_root_hash;
}

fn run_create_contract(
    executor: &mut ExecutorV2,
    global_state: &LmdbGlobalState,
    pre_state_hash: Digest,
    install_contract_request: InstallContractRequest,
) -> InstallContractResult {
    executor
        .install_contract(pre_state_hash, global_state, install_contract_request)
        .expect("Succeed")
}

fn run_wasm_session(
    executor: &mut ExecutorV2,
    global_state: &LmdbGlobalState,
    pre_state_hash: Digest,
    execute_request: ExecuteRequest,
) -> ExecuteWithProviderResult {
    let result = executor
        .execute_with_provider(pre_state_hash, global_state, execute_request)
        .expect("Succeed");

    if let Some(host_error) = result.host_error {
        panic!("Host error: {host_error:?}")
    }

    result
}

#[test]
fn backwards_compatibility() {
    let (mut global_state, post_state_hash, _temp) = {
        let fixture_name = "counter_contract";
        // /Users/michal/Dev/casper-node/execution_engine_testing/tests/fixtures/counter_contract/
        // global_state/data.lmdb
        let lmdb_fixtures_base_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../")
            .join("../")
            .join("execution_engine_testing")
            .join("tests")
            .join("fixtures");
        assert!(lmdb_fixtures_base_dir.exists());

        let source = lmdb_fixtures_base_dir.join("counter_contract");
        let to = tempfile::tempdir().expect("should create temp dir");
        fs_extra::copy_items(&[source], &to, &dir::CopyOptions::default())
            .expect("should copy global state fixture");

        let path_to_state = to.path().join(fixture_name).join("state.json");

        let lmdb_fixture_state: serde_json::Value =
            serde_json::from_reader(File::open(path_to_state).unwrap()).unwrap();
        let post_state_hash =
            Digest::from_hex(lmdb_fixture_state["post_state_hash"].as_str().unwrap()).unwrap();

        let path_to_gs = to.path().join(fixture_name).join("global_state");

        const DEFAULT_LMDB_PAGES: usize = 256_000_000;
        const DEFAULT_MAX_READERS: u32 = 512;

        let environment = LmdbEnvironment::new(
            &path_to_gs,
            16384 * DEFAULT_LMDB_PAGES,
            DEFAULT_MAX_READERS,
            true,
        )
        .expect("should create LmdbEnvironment");

        let trie_store =
            LmdbTrieStore::open(&environment, None).expect("should open LmdbTrieStore");
        (
            LmdbGlobalState::new(
                Arc::new(environment),
                Arc::new(trie_store),
                post_state_hash,
                100,
                false,
            ),
            post_state_hash,
            to,
        )
    };

    let result = global_state.query(QueryRequest::new(
        post_state_hash,
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        Vec::new(),
    ));
    let value = match result {
        QueryResult::RootNotFound => todo!(),
        QueryResult::ValueNotFound(value) => panic!("Value not found: {:?}", value),
        QueryResult::Success { value, .. } => value,
        QueryResult::Failure(failure) => panic!("Failed to query: {:?}", failure),
    };

    //
    // Calling legacy contract directly by it's address
    //

    let mut state_root_hash = post_state_hash;

    let value = match *value {
        StoredValue::Account(account) => account,
        _ => panic!("Expected CLValue"),
    };

    let counter_hash = match value.named_keys().get("counter") {
        Some(Key::Hash(hash_address)) => hash_address,
        _ => panic!("Expected counter URef"),
    };

    let mut executor = make_executor();
    let address_generator = make_address_generator();

    // Calling v1 vm directly by hash is not currently supported (i.e. disabling vm1 runtime, and
    // allowing vm1 direct calls may circumvent chainspec setting) let execute_request =
    // base_execute_builder()     .with_target(ExecutionKind::Stored {
    //         address: *counter_hash,
    //         entry_point: "counter_get".to_string(),
    //     })
    //     .with_input(runtime_args.into())
    //     .with_gas_limit(DEFAULT_GAS_LIMIT)
    //     .with_transferred_value(0)
    //     .with_shared_address_generator(Arc::clone(&address_generator))
    //     .with_state_hash(state_root_hash)
    //     .with_block_height(1)
    //     .with_parent_block_hash(BlockHash::new(Digest::hash(b"block1")))
    //     .build()
    //     .expect("should build");
    // let res = run_wasm_session(
    //     &mut executor,
    //     &mut global_state,
    //     state_root_hash,
    //     execute_request,
    // );
    // state_root_hash = global_state
    //     .commit_effects(state_root_hash, res.effects().clone())
    //     .expect("Should commit");

    //
    // Instantiate v2 runtime proxy contract
    //
    let input_data = counter_hash.to_vec();
    let install_request: InstallContractRequest = base_install_request_builder()
        .with_wasm_bytes(read_wasm("vm2_legacy_counter_proxy.wasm"))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_input(input_data.into())
        .with_state_hash(state_root_hash)
        .with_block_height(2)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block2")))
        .build()
        .expect("should build");

    let create_result = run_create_contract(
        &mut executor,
        &mut global_state,
        state_root_hash,
        install_request,
    );

    state_root_hash = create_result.post_state_hash();

    let proxy_address = *create_result.smart_contract_addr();

    // Call v2 contract

    let call_request = base_execute_builder()
        .with_target(ExecutionKind::Stored {
            address: proxy_address,
            entry_point: "perform_test".to_string(),
        })
        .with_input(Bytes::new())
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_state_hash(state_root_hash)
        .with_block_height(3)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block3")))
        .build()
        .expect("should build");

    run_wasm_session(
        &mut executor,
        &mut global_state,
        state_root_hash,
        call_request,
    );
}

// host function tests

fn call_dummy_host_fn_by_name(
    host_function_name: &str,
    gas_limit: u64,
) -> Result<InstallContractResult, InstallContractError> {
    let executor = {
        let execution_engine_v1 = ExecutionEngineV1::default();
        let default_wasm_config = WasmV2Config::default();
        let wasm_config = WasmV2Config::new(
            default_wasm_config.max_memory(),
            default_wasm_config.opcode_costs(),
            HostFunctionCostsV2 {
                read: HostFunctionV2::fixed(1),
                write: HostFunctionV2::fixed(1),
                remove: HostFunctionV2::fixed(1),
                copy_input: HostFunctionV2::fixed(1),
                ret: HostFunctionV2::fixed(1),
                create: HostFunctionV2::fixed(1),
                transfer: HostFunctionV2::fixed(1),
                env_balance: HostFunctionV2::fixed(1),
                upgrade: HostFunctionV2::fixed(1),
                call: HostFunctionV2::fixed(1),
                print: HostFunctionV2::fixed(1),
                emit: HostFunctionV2::fixed(1),
                env_info: HostFunctionV2::fixed(1),
            },
        );
        let executor_config = ExecutorConfigBuilder::default()
            .with_memory_limit(17)
            .with_executor_kind(ExecutorKind::Compiled)
            .with_wasm_config(wasm_config)
            .with_storage_costs(StorageCosts::default())
            .with_message_limits(MessageLimits::default())
            .build()
            .expect("Should build");
        ExecutorV2::new(executor_config, Arc::new(execution_engine_v1))
    };

    let (mut global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let input_data = borsh::to_vec(&(host_function_name.to_owned(),))
        .map(Bytes::from)
        .unwrap();

    let create_request = InstallContractRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_gas_limit(gas_limit)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_host.wasm"))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_input(input_data)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");

    executor.install_contract(state_root_hash, &mut global_state, create_request)
}

fn assert_consumes_gas(host_function_name: &str) {
    let result = call_dummy_host_fn_by_name(host_function_name, 1);
    assert!(result.is_err_and(|e| match e {
        InstallContractError::Constructor {
            host_error: CallError::CalleeGasDepleted,
        } => true,
        _ => false,
    }));
}

#[test]
fn host_functions_consume_gas() {
    assert_consumes_gas("get_caller");
    assert_consumes_gas("get_block_time");
    assert_consumes_gas("get_transferred_value");
    assert_consumes_gas("get_balance_of");
    assert_consumes_gas("call");
    assert_consumes_gas("input");
    assert_consumes_gas("create");
    assert_consumes_gas("print");
    assert_consumes_gas("read");
    assert_consumes_gas("ret");
    assert_consumes_gas("transfer");
    assert_consumes_gas("upgrade");
    assert_consumes_gas("write");
}

#[allow(dead_code)]
fn write_n_bytes_at_limit(
    bytes_len: u64,
    gas_limit: u64,
) -> Result<InstallContractResult, InstallContractError> {
    let executor = {
        let execution_engine_v1 = ExecutionEngineV1::default();
        let default_wasm_config = WasmV2Config::default();
        let wasm_config = WasmV2Config::new(
            default_wasm_config.max_memory(),
            default_wasm_config.opcode_costs(),
            HostFunctionCostsV2 {
                read: HostFunctionV2::fixed(0),
                write: HostFunctionV2::fixed(0),
                remove: HostFunctionV2::fixed(0),
                copy_input: HostFunctionV2::fixed(0),
                ret: HostFunctionV2::fixed(0),
                create: HostFunctionV2::fixed(0),
                transfer: HostFunctionV2::fixed(0),
                env_balance: HostFunctionV2::fixed(0),
                upgrade: HostFunctionV2::fixed(0),
                call: HostFunctionV2::fixed(0),
                print: HostFunctionV2::fixed(0),
                emit: HostFunctionV2::fixed(0),
                env_info: HostFunctionV2::fixed(0),
            },
        );
        let executor_config = ExecutorConfigBuilder::default()
            .with_memory_limit(17)
            .with_executor_kind(ExecutorKind::Compiled)
            .with_wasm_config(wasm_config)
            .with_storage_costs(StorageCosts::new(1))
            .with_message_limits(MessageLimits::default())
            .build()
            .expect("Should build");
        ExecutorV2::new(executor_config, Arc::new(execution_engine_v1))
    };

    let (mut global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let input_data = borsh::to_vec(&(bytes_len,)).map(Bytes::from).unwrap();

    let create_request = InstallContractRequestBuilder::default()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_gas_limit(gas_limit)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_host.wasm"))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new_with_write".to_string())
        .with_input(input_data)
        .with_chain_name(DEFAULT_CHAIN_NAME)
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");

    executor.install_contract(state_root_hash, &mut global_state, create_request)
}

// #[test]
// fn consume_gas_on_write() {
//     let successful_write = write_n_bytes_at_limit(50, 10_000);
//     assert!(successful_write.is_ok());

//     let out_of_gas_write_exceeded_gas_limit = write_n_bytes_at_limit(50, 10);
//     assert!(out_of_gas_write_exceeded_gas_limit.is_err_and(|e| match e {
//         InstallContractError::Constructor {
//             host_error: HostError::CalleeGasDepleted,
//         } => true,
//         _ => false,
//     }));
// }

#[test]
fn non_existing_smart_contract_does_not_panic() {
    let address_generator = make_address_generator();
    let executor = make_executor();
    let (mut global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let non_existing_address = [255; 32];
    let execute_request = base_execute_builder()
        .with_target(ExecutionKind::Stored {
            address: non_existing_address,
            entry_point: "non_existing".to_string(),
        })
        .with_input(Bytes::new())
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .build()
        .expect("should build");

    let result = executor
        .execute_with_provider(state_root_hash, &mut global_state, execute_request)
        .expect_err("Failure");

    assert!(matches!(
        result,
        ExecuteWithProviderError::Execute(execute_error) if matches!(execute_error, ExecuteError::CodeNotFound(address) if address == non_existing_address)));
}

fn expect_successful_execution(
    executor: &mut ExecutorV2,
    global_state: &LmdbGlobalState,
    pre_state_hash: Digest,
    execute_request: ExecuteRequest,
) -> ExecuteWithProviderResult {
    let result = executor
        .execute_with_provider(pre_state_hash, global_state, execute_request)
        .expect("execute_with_provider should succeed");
    if let Some(host_error) = result.host_error {
        panic!("Host error: {host_error:?}");
    }
    result
}

#[test]
fn casper_return_writes_to_execution_journal() {
    let address_generator = make_address_generator();
    let mut executor = make_executor();
    let (global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();

    // Create a contract that will be used to test the ret host function
    let input_data = borsh::to_vec(&("write".to_string(),))
        .map(Bytes::from)
        .unwrap();

    let install_request = base_install_request_builder()
        .with_wasm_bytes(read_wasm("vm2_host.wasm"))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_input(input_data)
        .build()
        .expect("should build");

    let create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        install_request,
    );

    let contract_address = *create_result.smart_contract_addr();
    state_root_hash = create_result.post_state_hash();

    // Execute the contract to trigger the return
    let execute_request = base_execute_builder()
        .with_target(ExecutionKind::Stored {
            address: contract_address,
            entry_point: "ret".to_string(),
        })
        .with_input(Bytes::new())
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .build()
        .expect("should build");

    let execute_result = expect_successful_execution(
        &mut executor,
        &global_state,
        state_root_hash,
        execute_request,
    );

    // Check that the effects contain a Ret transform
    let effects = execute_result.effects();
    let transforms = effects.transforms();

    let ret_transforms: Vec<&TransformV2> = transforms
        .iter()
        .filter(|transform| matches!(transform.kind(), TransformKindV2::Ret(_)))
        .collect();
    assert_eq!(ret_transforms.len(), 1);
    let ret_transform = ret_transforms
        .first()
        .expect("Expected to find a Ret transform in the effects");

    match ret_transform.kind() {
        TransformKindV2::Ret(RetValue::Bytes(bytes)) => {
            // The ret function in the test contract calls casper::ret with [1, 2, 3] data
            assert_eq!(
                bytes.as_slice(),
                &[1u8, 2, 3],
                "Return data should match what was passed to casper::ret"
            );
        }
        _ => panic!("Expected Ret transform kind"),
    }
    assert_eq!(
        ret_transform.key(),
        &Key::Hash(contract_address.into()),
        "Ret transform should be under the callee (contract) key"
    );
}

#[test]
fn calling_upgrade_contract_should_produce_ret_and_call_result() {
    let mut executor = make_executor();
    let upgradable_address;
    let (global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();
    let input_data = borsh::to_vec(&(0u8,)).map(Bytes::from).unwrap();

    let create_request = base_install_request_builder()
        .with_wasm_bytes(read_wasm("vm2_upgradable.wasm"))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_input(input_data)
        .build()
        .expect("should build");

    let create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        create_request,
    );

    upgradable_address = *create_result.smart_contract_addr();

    state_root_hash = global_state
        .commit_effects(state_root_hash, create_result.effects().clone())
        .expect("Should commit");
    let binding = read_wasm("vm2_upgradable_v2.wasm");
    let new_code = binding.as_ref();

    let execute_request = base_execute_builder()
        .with_transferred_value(0)
        .with_target(ExecutionKind::Stored {
            address: upgradable_address,
            entry_point: "perform_upgrade".to_string(),
        })
        .with_gas_limit(DEFAULT_GAS_LIMIT * 10)
        .with_serialized_input((new_code,))
        .with_shared_address_generator(Arc::clone(&address_generator))
        .build()
        .expect("should build");
    let upgrade_result = expect_successful_execution(
        &mut executor,
        &global_state,
        state_root_hash,
        execute_request,
    );

    let transforms = upgrade_result.effects().transforms();
    let ep_calls_and_rets = get_ep_calls_and_rets(transforms);
    assert_eq!(ep_calls_and_rets.len(), 4);

    let expected_call_1 = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::EntryPointCalled(
            Some(*create_result.smart_contract_addr()),
            "perform_upgrade".to_string(),
        ),
    );
    let expected_call_2 = TransformV2::new(
        Key::Hash(*create_result.smart_contract_addr()),
        TransformKindV2::EntryPointCalled(
            Some(*create_result.smart_contract_addr()),
            "migrate".to_string(),
        ),
    );
    let ret_1 = TransformV2::new(
        Key::Hash(*create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Unit),
    );
    let ret_2 = TransformV2::new(
        Key::Hash(*create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Unit),
    );
    assert_eq!(
        ep_calls_and_rets,
        vec![expected_call_1, expected_call_2, ret_1, ret_2]
    );
}

#[test]
fn calling_constructor_method_should_produce_ret_and_call_result() {
    let mut executor = make_executor();

    let (global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let block_time_1 = Timestamp::now().into();

    let create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_counter.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("default".to_string())
        .with_block_time(block_time_1)
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");

    let create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        create_request,
    );
    let transforms = create_result.effects().transforms();
    let ep_calls_and_rets = get_ep_calls_and_rets(transforms);
    assert_eq!(ep_calls_and_rets.len(), 2);
    let constructor_called = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::EntryPointCalled(
            Some(*create_result.smart_contract_addr()),
            "default".to_string(),
        ),
    );
    let ret = TransformV2::new(
        Key::Hash(*create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Unit),
    );
    assert_eq!(ep_calls_and_rets, vec![constructor_called, ret]);
}

#[test]
fn contract_calling_different_contract_should_produce_ret_and_call_result() {
    let mut executor = make_executor();

    let (global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let block_time_1 = Timestamp::now().into();
    let input = borsh::to_vec(&(0u32,)).map(Bytes::from).unwrap();
    let counter_create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_counter.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_block_time(block_time_1)
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .with_input(input)
        .build()
        .expect("should build");

    let counter_create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        counter_create_request,
    );

    state_root_hash = global_state
        .commit_effects(state_root_hash, counter_create_result.effects().clone())
        .expect("Should commit");

    let caller_create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_counter_caller.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("create".to_string())
        .with_block_time(block_time_1)
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");

    let caller_create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        caller_create_request,
    );

    state_root_hash = global_state
        .commit_effects(state_root_hash, caller_create_result.effects().clone())
        .expect("Should commit");

    let execute_caller_request = base_execute_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_target(ExecutionKind::Stored {
            address: *caller_create_result.smart_contract_addr(),
            entry_point: "inc_and_get".to_string(),
        })
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_block_time(Timestamp::now().into())
        .with_state_hash(state_root_hash)
        .with_block_height(2)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block")))
        .with_serialized_input((counter_create_result.smart_contract_addr(),))
        .build()
        .expect("should build");

    let result = expect_successful_execution(
        &mut executor,
        &global_state,
        state_root_hash,
        execute_caller_request,
    );
    let b = 1_u32.to_le_bytes();
    assert_eq!(result.output().unwrap().iter().as_slice(), b.as_slice());
    let transforms = result.effects().transforms();
    let ep_calls_and_rets = get_ep_calls_and_rets(transforms);
    assert_eq!(ep_calls_and_rets.len(), 6);

    let inc_and_get_call = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::EntryPointCalled(
            Some(*caller_create_result.smart_contract_addr()),
            "inc_and_get".to_string(),
        ),
    );
    let increment_call = TransformV2::new(
        Key::Hash(*caller_create_result.smart_contract_addr()),
        TransformKindV2::EntryPointCalled(
            Some(*counter_create_result.smart_contract_addr()),
            "increment".to_string(),
        ),
    );
    let increment_return = TransformV2::new(
        Key::Hash(*counter_create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Unit),
    );
    let get_call = TransformV2::new(
        Key::Hash(*caller_create_result.smart_contract_addr()),
        TransformKindV2::EntryPointCalled(
            Some(*counter_create_result.smart_contract_addr()),
            "get".to_string(),
        ),
    );
    let get_return = TransformV2::new(
        Key::Hash(*counter_create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Bytes(b.as_slice().into())),
    );

    let inc_and_get_return = TransformV2::new(
        Key::Hash(*caller_create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Bytes(b.as_slice().into())),
    );

    assert_eq!(
        ep_calls_and_rets,
        vec![
            inc_and_get_call,
            increment_call,
            increment_return,
            get_call,
            get_return,
            inc_and_get_return
        ]
    );
}

#[test]
fn calling_session_should_produce_entry_point_called_and_ret() {
    let mut executor = make_executor();

    let (global_state, state_root_hash, _tempdir) = make_global_state_with_genesis();

    let address_generator = make_address_generator();

    let execute_request = base_execute_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_target(ExecutionKind::SessionBytes(read_wasm(
            "vm2_do_nothing_session.wasm",
        )))
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");
    let result = expect_successful_execution(
        &mut executor,
        &global_state,
        state_root_hash,
        execute_request,
    );

    let transforms = result.effects().transforms();
    let ep_calls_and_rets = get_ep_calls_and_rets(transforms);
    assert_eq!(ep_calls_and_rets.len(), 2);
    let call = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::EntryPointCalled(None, DEFAULT_ENTRY_POINT_NAME.to_string()),
    );
    let session_return = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::Ret(RetValue::Unit),
    );

    assert_eq!(ep_calls_and_rets, vec![call, session_return]);
}

/// Test: 3-level nesting (account → counter-caller → counter × 2 calls).
///
/// The counter-caller contract calls counter's `increment` then `get`, so the journal
/// shows 3 EC-Ret pairs across 2 depths of stored-contract nesting.
#[test]
fn vm2_three_levels_of_contract_calls_produce_journal() {
    let mut executor = make_executor();
    let (global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();
    let address_generator = make_address_generator();

    let block_time_1 = Timestamp::now().into();

    let counter_create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_counter.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("new".to_string())
        .with_block_time(block_time_1)
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .with_input(borsh::to_vec(&(0u32,)).map(Bytes::from).unwrap())
        .build()
        .expect("should build");

    let counter_create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        counter_create_request,
    );
    state_root_hash = global_state
        .commit_effects(state_root_hash, counter_create_result.effects().clone())
        .expect("Should commit");

    let caller_create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_counter_caller.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("create".to_string())
        .with_block_time(block_time_1)
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");
    let caller_create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        caller_create_request,
    );
    state_root_hash = global_state
        .commit_effects(state_root_hash, caller_create_result.effects().clone())
        .expect("Should commit");

    // Call counter-caller (depth 1) which calls counter twice (depth 2):
    // account → counter-caller.inc_and_get  [EC + Ret]
    //   → counter.increment                 [EC + Ret]
    //   → counter.get                       [EC + Ret]
    // = 3 distinct EntryPointCalled + 3 corresponding Ret entries
    let execute_request = base_execute_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_target(ExecutionKind::Stored {
            address: *caller_create_result.smart_contract_addr(),
            entry_point: "inc_and_get".to_string(),
        })
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_block_time(Timestamp::now().into())
        .with_state_hash(state_root_hash)
        .with_block_height(2)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block")))
        .with_serialized_input((counter_create_result.smart_contract_addr(),))
        .build()
        .expect("should build");

    let result = expect_successful_execution(
        &mut executor,
        &global_state,
        state_root_hash,
        execute_request,
    );
    let ep_calls_and_rets = get_ep_calls_and_rets(result.effects().transforms());
    let b = 1_u32.to_le_bytes();
    let inc_and_get_call = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::EntryPointCalled(
            Some(*caller_create_result.smart_contract_addr()),
            "inc_and_get".to_string(),
        ),
    );
    let increment_call = TransformV2::new(
        Key::Hash(*caller_create_result.smart_contract_addr()),
        TransformKindV2::EntryPointCalled(
            Some(*counter_create_result.smart_contract_addr()),
            "increment".to_string(),
        ),
    );
    let increment_return = TransformV2::new(
        Key::Hash(*counter_create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Unit),
    );
    let get_call = TransformV2::new(
        Key::Hash(*caller_create_result.smart_contract_addr()),
        TransformKindV2::EntryPointCalled(
            Some(*counter_create_result.smart_contract_addr()),
            "get".to_string(),
        ),
    );
    let get_return = TransformV2::new(
        Key::Hash(*counter_create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Bytes(b.as_slice().into())),
    );
    let inc_and_get_return = TransformV2::new(
        Key::Hash(*caller_create_result.smart_contract_addr()),
        TransformKindV2::Ret(RetValue::Bytes(b.as_slice().into())),
    );
    assert_eq!(
        ep_calls_and_rets,
        vec![
            inc_and_get_call,
            increment_call,
            increment_return,
            get_call,
            get_return,
            inc_and_get_return,
        ]
    );
}

/// Test: When a stored contract fails (bad input → deserialization panic → trap),
/// its EntryPointCalled appears in the journal but no Ret is recorded.
#[test]
fn vm2_failed_call_shows_entry_point_called_without_ret() {
    let mut executor = make_executor();
    let (global_state, mut state_root_hash, _tempdir) = make_global_state_with_genesis();
    let address_generator = make_address_generator();

    // Install counter-caller (does not need a real counter for this test)
    let caller_create_request = base_install_request_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_wasm_bytes(read_wasm("vm2_counter_caller.wasm").clone())
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_transferred_value(0)
        .with_entry_point("create".to_string())
        .with_block_time(Timestamp::now().into())
        .with_state_hash(Digest::from_raw([0; 32]))
        .with_block_height(1)
        .with_parent_block_hash(BlockHash::new(Digest::from_raw([0; 32])))
        .build()
        .expect("should build");

    let caller_create_result = run_create_contract(
        &mut executor,
        &global_state,
        state_root_hash,
        caller_create_request,
    );
    state_root_hash = global_state
        .commit_effects(state_root_hash, caller_create_result.effects().clone())
        .expect("Should commit");

    // Call counter-caller.inc_and_get with EMPTY input. The contract expects a serialized
    // Address as input; empty bytes cause borsh deserialization to fail → WASM trap.
    // With EntryPointCalled recorded before the tracking-copy fork, the EC appears in
    // the returned effects even though the call failed.
    let execute_request = base_execute_builder()
        .with_initiator(*DEFAULT_ACCOUNT_HASH)
        .with_caller_key(Key::Account(*DEFAULT_ACCOUNT_HASH))
        .with_gas_limit(DEFAULT_GAS_LIMIT)
        .with_transaction_hash(TRANSACTION_HASH)
        .with_target(ExecutionKind::Stored {
            address: *caller_create_result.smart_contract_addr(),
            entry_point: "inc_and_get".to_string(),
        })
        .with_transferred_value(0)
        .with_shared_address_generator(Arc::clone(&address_generator))
        .with_block_time(Timestamp::now().into())
        .with_state_hash(state_root_hash)
        .with_block_height(2)
        .with_parent_block_hash(BlockHash::new(Digest::hash(b"block")))
        .with_input(Bytes::new()) // deliberately empty — triggers deserialization failure
        .build()
        .expect("should build");

    let result = executor
        .execute_with_provider(state_root_hash, &global_state, execute_request)
        .expect("execute_with_provider should succeed even for trapping calls");

    // The call must have failed
    assert!(
        result.host_error.is_some(),
        "Expected a host error due to wasm trap"
    );

    // EntryPointCalled is present — the call was attempted
    let ep_calls_and_rets = get_ep_calls_and_rets(result.effects().transforms());
    let expected_ec = TransformV2::new(
        Key::Account(*DEFAULT_ACCOUNT_HASH),
        TransformKindV2::EntryPointCalled(
            Some(*caller_create_result.smart_contract_addr()),
            "inc_and_get".to_string(),
        ),
    );
    assert_eq!(ep_calls_and_rets, vec![expected_ec]);
}

fn get_ep_calls_and_rets(transforms: &[TransformV2]) -> Vec<TransformV2> {
    transforms
        .iter()
        .filter(|transform| {
            matches!(
                transform.kind(),
                TransformKindV2::EntryPointCalled(_, _) | TransformKindV2::Ret(_)
            )
        })
        .cloned()
        .collect()
}
