[package]
name = "casper-sdk-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-sdk = {path = "../sdk" }
codegen = "0.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
indexmap = "2.1.0"
syn = "2"

[dev-dependencies]
trybuild = "1"
tempfile = "3.2.0"
borsh = { version = "1.3.0", features = ["derive"] }

[build-dependencies]
