[package]
name = "trie-compact"
version = "0.1.0"
authors = ["Daniel Werner <dan@casperlabs.io>"]
edition = "2018"

[dependencies]
anyhow = "1"
casper-contract = { path = "../../smart_contracts/contract", default-features = false, features = ["std"] }
casper-execution-engine = { path = "../../execution_engine" }
casper-hashing = { path = "../../hashing" }
casper-types = { path = "../../types", features = ["std"] }
lmdb = "0.8.0"
retrieve-state = { path = "../retrieve-state" }
structopt = "0.3.23"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.34"
env_logger = "0.8"

[[bin]]
name = "trie-compact"
