use core::{mem, ptr::NonNull};

use crate::{
    abi::{Declaration, Definitions},
    compat::types::CLType,
    linkme::distributed_slice,
    schema::{Schema, SchemaMessage, SchemaType},
    serializers::AbiConvention,
};

#[derive(Debug)]
pub struct AbiType {
    pub type_name: &'static str,
    pub cl_type: fn() -> CLType,
}

impl AbiType {
    #[inline]
    pub fn cl_type(&self) -> CLType {
        (self.cl_type)()
    }
}
#[derive(Debug)]
pub struct AbiParam {
    pub name: &'static str,
    pub decl: AbiType,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct AbiLocation {
    pub file: &'static str,
    pub line: u32,
    pub col: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum AbiKind {
    /// struct SmartContract {}
    SmartContract,
    /// impl `trait_name` for
    TraitImpl { trait_name: &'static str },
    /// fn call() {}
    Function,
}

#[derive(Debug)]
pub enum AbiReceiver {
    /// &self
    ByRef,
    /// &mut self
    ByMutRef,
    /// self
    ByVal,
}

#[derive(Debug)]
pub struct AbiEntryPoint {
    /// Function name
    pub name: &'static str,
    /// Export name
    ///
    /// This may be different than `name` in case of trait impl methods.
    pub export_name: &'static str,
    pub receiver: Option<AbiReceiver>,
    pub params: &'static [AbiParam],

    pub abi_convention: AbiConvention,
    pub is_constructor: bool,
    pub is_payable: bool,

    pub result_decl: AbiType,
    pub kind: AbiKind,

    pub location: AbiLocation,
    /// The actual callable export
    pub fptr: fn() -> (),
}

#[derive(Debug)]
pub struct AbiSmartContract {
    pub struct_name: &'static str,
    pub abi_convention: AbiConvention,
    pub cl_type: fn() -> CLType,
}

#[derive(Debug)]
pub enum AbiItem {
    /// Smart Contract
    ///
    /// #[casper(contract_state)]
    SmartContract(AbiSmartContract),
    /// impl Foo { fn method(params) -> result_decl }
    EntryPoint(AbiEntryPoint),
}

impl AbiItem {
    pub fn as_smart_contract(&self) -> Option<&AbiSmartContract> {
        match self {
            AbiItem::SmartContract(smart_contract) => Some(smart_contract),
            _ => None,
        }
    }

    pub fn as_abi_entry_point(&self) -> Option<&AbiEntryPoint> {
        match self {
            AbiItem::EntryPoint(entry_point) => Some(entry_point),
            _ => None,
        }
    }
}

#[distributed_slice]
#[linkme(crate = crate::linkme)]
pub static ABI_ITEMS: [AbiItem] = [..];

#[derive(Debug, Clone)]
pub struct Message {
    pub name: &'static str,
    pub decl: &'static str,
}

#[distributed_slice]
#[linkme(crate = crate::linkme)]
pub static MESSAGES: [Message] = [..];

/// All of the entry points generated by proc macro will be registered here.
#[distributed_slice]
#[linkme(crate = crate::linkme)]
pub static ENTRYPOINTS: [fn() -> crate::schema::SchemaEntryPoint] = [..];

#[distributed_slice]
#[linkme(crate = crate::linkme)]
pub static ABI_COLLECTORS: [fn(&mut crate::abi::Definitions)] = [..];

#[derive(Debug, Clone)]
pub struct NamedKey {
    pub name: &'static str,
    pub decl: fn() -> Declaration,
}

#[distributed_slice]
#[linkme(crate = crate::linkme)]
pub static NAMED_KEYS: [NamedKey] = [..];

pub fn casper_collect_schema() -> Schema {
    // Collect definitions
    let definitions = {
        let mut definitions = Definitions::default();

        for abi_collector in ABI_COLLECTORS {
            abi_collector(&mut definitions);
        }

        definitions
    };

    // Collect messages
    let messages = {
        let mut messages = Vec::new();

        for message in MESSAGES {
            messages.push(SchemaMessage {
                name: message.name.to_owned(),
                decl: message.decl.to_owned(),
            });
        }

        messages
    };

    // Collect named keys
    let named_keys = {
        let mut named_keys = Vec::new();

        for named_key in NAMED_KEYS {
            named_keys.push(crate::schema::SchemaStableKey {
                name: named_key.name.to_owned(),
                decl: (named_key.decl)(),
            });
        }

        named_keys
    };

    // Collect entrypoints
    let entry_points = {
        let mut entry_points = Vec::new();
        for entrypoint in ENTRYPOINTS {
            entry_points.push(entrypoint());
        }
        entry_points
    };

    // Construct a schema object from the extracted information
    Schema {
        name: "contract".to_string(),
        version: None,
        type_: SchemaType::Contract {
            state: "Contract".to_string(),
        },
        definitions,
        entry_points,
        messages,
        named_keys,
    }
}

/// This function is called by the host to collect the schema from the contract.
///
/// This is considered internal implementation detail and should not be used directly.
/// Primary user of this API is `cargo-casper` tool that will use it to extract schema from the
/// contract.
///
/// # Safety
/// Pointer to json bytes passed to the callback is valid only within the scope of that function.
#[export_name = "__cargo_casper_collect_schema"]
pub unsafe extern "C" fn cargo_casper_collect_schema(size_ptr: *mut u64) -> *mut u8 {
    let schema = casper_collect_schema();
    // Write the schema using the provided writer
    let mut json_bytes = serde_json::to_vec(&schema).expect("Serialized schema");
    NonNull::new(size_ptr)
        .expect("expected non-null ptr")
        .write(json_bytes.len().try_into().expect("usize to u64"));
    let ptr = json_bytes.as_mut_ptr();
    mem::forget(json_bytes);
    ptr
}

pub const fn extract_export_name_from_meta(s: &str) -> &str {
    // Byte pattern to search for: export_name
    const KEY: &[u8] = b"export_name";

    let bytes = s.as_bytes();
    let n = bytes.len();

    // 1) Find "export_name" using manual byte comparison (no slicing/equality ops)
    let mut i = 0usize;
    let mut found = false;
    while i + KEY.len() <= n {
        let mut j = 0usize;
        while j < KEY.len() && bytes[i + j] == KEY[j] {
            j += 1;
        }
        if j == KEY.len() {
            found = true;
            break;
        }
        i += 1;
    }
    if !found {
        return "";
    }
    i += KEY.len();

    // 2) Skip whitespace
    while i < n && (bytes[i] == b' ' || bytes[i] == b'\t') {
        i += 1;
    }

    // 3) Expect '='
    if i >= n || bytes[i] != b'=' {
        return "";
    }
    i += 1;

    // 4) Skip whitespace
    while i < n && (bytes[i] == b' ' || bytes[i] == b'\t') {
        i += 1;
    }

    // 5) Expect opening quote
    if i >= n || (bytes[i] != b'"' && bytes[i] != b'\'') {
        return "";
    }
    let quote = bytes[i];
    i += 1;

    // 6) Scan until closing quote (handle escapes) and capture start/end indices
    let start = i;
    while i < n {
        let b = bytes[i];
        if b == quote {
            // Return a &str to the substring [start, i)
            // SAFETY: `s` is valid, and `start..i` is within bounds and points to valid UTF-8
            // because it's a subslice of a valid &str cut at byte boundaries.
            unsafe {
                let ptr = s.as_ptr().add(start);
                let len = i - start;
                let subslice = core::slice::from_raw_parts(ptr, len);
                return core::str::from_utf8_unchecked(subslice);
            }
        }
        if b == b'\\' && i + 1 < n {
            // Skip escaped char
            i += 2;
        } else {
            i += 1;
        }
    }

    // If we get here, no closing quote found
    ""
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_double_quotes() {
        assert_eq!(
            extract_export_name_from_meta(r#"#[export_name = "foo"]"#),
            "foo"
        );
    }

    #[test]
    fn parses_single_quotes() {
        assert_eq!(
            extract_export_name_from_meta(r#"#[export_name='bar']"#),
            "bar"
        );
    }

    #[test]
    fn handles_escapes() {
        assert_eq!(
            extract_export_name_from_meta(r#"#[export_name="a\"b"]"#),
            r#"a\"b"#
        );
    }

    #[test]
    fn returns_empty_on_mismatch() {
        assert_eq!(extract_export_name_from_meta(r#"#[nope="x"]"#), "");
    }

    // Demonstrate it’s usable in const context:
    const NAME: &str = extract_export_name_from_meta(r#"#[export_name = "foo"]"#);
    #[test]
    fn const_ok() {
        assert_eq!(NAME, "foo");
    }
}
