#! /usr/bin/env bash

set -e

# Default Variables
# ---
DEFAULT_USERNAME="casperlabs"
DEFAULT_DATA_DIRECTORY="/var/lib/${DEFAULT_USERNAME}"

# User Creation
# ---
# Assure DEFAULT_USERNAME user exists
if id -u ${DEFAULT_USERNAME} >/dev/null 2>&1; then
    echo "User ${DEFAULT_USERNAME} already exists."
else
    adduser --no-create-home --group --system ${DEFAULT_USERNAME}
fi

# Creation of Files/Directories
# ---
# Assure DEFAULT_DATA_DIRECTORY is available for state data
if [ -d ${DEFAULT_DATA_DIRECTORY} ] ; then
    echo "Directory ${DEFAULT_DATA_DIRECTORY} already exists."
else
    mkdir -p ${DEFAULT_DATA_DIRECTORY}
fi

# Files/Directories Owner
# ---
# Assure DEFAULT_DATA_DIRECTORY is owned by DEFAULT_USERNAME
if [ -d ${DEFAULT_DATA_DIRECTORY} ] ; then
    chown ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_DATA_DIRECTORY}
fi
