pipeline:
  identifier: Build_casper_network_casper_node_1701271611457
  name: Build casper-node
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: org.casperdrone_github_connector
        repoName: casper-network/casper-node
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: setup
                  spec:
                    connectorRef: dockerhub
                    image: casperlabs/node-build-u1804
                    shell: Bash
                    command: |-
                      make setup
                      cargo install elfx86exts --version 0.5.0
                  timeout: ""
                  type: Run
                  description: copy of drone setup step
              - step:
                  type: Run
                  name: cargo-test-push
                  identifier: cargotestpush
                  spec:
                    connectorRef: dockerhub
                    image: casperlabs/node-build-u1804
                    shell: Bash
                    command: |-
                      make test CARGO_FLAGS=--release
                      make test-contracts CARGO_FLAGS=--release
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.casperkube
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
