pipeline:
  identifier: Build_casper_network_casper_node_1701271611457
  name: Build casper-node
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        connectorRef: org.casperdrone_github_connector
        repoName: casper-node
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build casper-node
                  identifier: cargotestpush
                  spec:
                    connectorRef: dockerhub
                    image: casperlabs/node-build-u1804
                    shell: Bash
                    command: |-
                      cargo install elfx86exts --version 0.5.0
                      make setup
                      make test CARGO_FLAGS=--release
                      make test-contracts CARGO_FLAGS=--release
                    resources:
                      limits:
                        memory: 16Gi
                        cpu: "12"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.casperkube
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
