[package]
name = "rpc-server-tests"
version = "0.1.0"
edition = "2018"
authors = ["Rafał Chabowski <rafal@casperlabs.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive = "1.0.0"
features = "0.10.0"
jsonschema = "0.12.1"
reqwest = { version = "0.11.4", features = ["json"] }
serde_json = "1.0.66"
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
