[package]
name = "casper-executor-wasm-host"
version = "1.0.0"
edition = "2021"
authors = ["Michał Papierski <michal@casper.network>"]
description = "Casper executor host package"
homepage = "https://casper.network"
repository = "https://github.com/casper-network/casper-node/tree/dev/executor/wasm_host"
license = "Apache-2.0"

[dependencies]
base16 = "0.2"
bytes = "1.10"
blake2 = { version = "0.10.6", default-features = false }
blake3 = { version = "1.5.0", default-features = false, features = ["pure"] }
bn = { version = "0.5", package = "zeropool-bn", default-features = false }
bnum = { version = "0.13.0", features = ["borsh", "num-integer", "num-traits"] }
borsh = { version = "1.5", features = ["derive"] }
sha2 = { version = "0.10.8", default-features = false }
keccak-asm = { version = "0.1.4", default-features = false }
casper-executor-wasm-common = { version = "1.0.0", path = "../wasm_common" }
casper-executor-wasm-interface = { version = "1.0.0", path = "../wasm_interface" }
casper-storage = { version = "4.0.0", path = "../../storage" }
casper-types = { version = "8.0.0", path = "../../types", features = ["std", "testing"] }
either = "1.15"
num-derive = { workspace = true }
num-traits = { workspace = true }
parking_lot = "0.12"
thiserror = "2"
tracing = "0.1"