[package]
name = "casper-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Michał Papierski <michal@casperlabs.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { version = "1.2.0", features = ["derive"] }
bytes = "1"
bitflags = "2.4.1"
const-fnv1a-hash = "1.1.0"
impl-trait-for-tuples = "0.2.2"
casper-sdk-sys = {path = "../sdk-sys" }
casper-executor-wasm-common = { path = "../../executor/wasm-common" }
# casper-macros = {path = "../macros" }

once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

clap = { version = "4", optional = true, features = ["derive"] }
thiserror = { version = "1", optional = true }

cfg-if = "1.0.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand  = "0.8.5"
once_cell = "1.19.0"
linkme = "0.3.26"

[features]
default = ["std"]
std = []

cli = ["clap", "thiserror"]
__abi_generator = []
