[package]
name = "dry-run-deploys"
version = "0.1.0"
authors = ["Daniel Werner <dan@casperlabs.io>"]
edition = "2018"

[dependencies]
anyhow = "1"
casper-contract = { path = "../../smart_contracts/contract", default-features = false, features = ["std"] }
casper-execution-engine = { path = "../../execution_engine" }
casper-hashing = { path = "../../hashing" }
casper-node = { path = "../../node" }
casper-types = { path = "../../types", features = ["std"] }
casper-engine-test-support = { path = "../../execution_engine_testing/test_support" }
hex = "0.4.3"
histogram = "0.6.9"
indicatif = "0.17.0-beta.1"
lmdb = "0.8.0"
log = "0.4.8"
num-rational = "0.4.0"
num-traits = "0.2.10"
once_cell = "1.5.2"
rand = "0.8.3"
reqwest = { version = "0.11.1", features = ["json"] }
retrieve-state = { path = "../retrieve-state" }
serde_json = "1"
serde = "1"
structopt = "0.3.23"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
version-sync = "0.9"
walkdir = "2"
