---
name: casper-node
# runs steps that are OK with normal rust based on ./rust-toolchain.toml
permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - trying
      - staging
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - dev
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup ubuntu
        run: |
          sudo apt-get -y install wabt

      - name: cache setup tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
            ~/.cargo/bin/cargo-audit
          key: setup-tools-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', 'smart_contracts/rust-toolchain', 'Makefile') }}
          restore-keys: |
            setup-tools-${{ runner.os }}-

      - name: setup
        run: make setup

      - uses: Swatinem/rust-cache@v2

      - name: check-format
        run: make check-format

      - name: doc
        run: make doc

      - name: lint
        run: make lint

      - name: audit
        run: make audit

      - name: check-std-features
        run: make check-std-features

      - name: check-testing-features
        run: make check-testing-features

  test:
    name: test
    runs-on: ubuntu-latest-big
    timeout-minutes: 60
    needs:
      - build_contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup ubuntu
        run: |
          sudo apt-get -y install wabt

      - name: cache setup tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
            ~/.cargo/bin/cargo-audit
          key: setup-tools-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', 'smart_contracts/rust-toolchain', 'Makefile') }}
          restore-keys: |
            setup-tools-${{ runner.os }}-

      - name: setup
        run: make setup

      - uses: Swatinem/rust-cache@v2

      - name: download smart contracts
        uses: actions/download-artifact@v4
        with:
          name: smart-contracts
          path: .

      - name: extract smart contracts
        run: tar -xzf smart-contracts.tar.gz

      - name: test
        run: make -j2 test-ci CARGO_FLAGS=--release CARGO_TEST_PROFILE_ENV='CARGO_PROFILE_RELEASE_LTO=false CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16'

  build_contracts:
    name: build-contracts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup ubuntu
        run: |
          sudo apt-get -y install wabt

      - name: cache setup tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
            ~/.cargo/bin/cargo-audit
          key: setup-tools-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', 'smart_contracts/rust-toolchain', 'Makefile') }}
          restore-keys: |
            setup-tools-${{ runner.os }}-

      - name: setup
        run: make setup

      - uses: Swatinem/rust-cache@v2

      - name: build smart contracts
        run: make build-test-artifacts CARGO_FLAGS=--release

      - name: archive smart contracts
        run: tar -czf smart-contracts.tar.gz resources/local/chainspec.toml target/wasm32-unknown-unknown/release/*.wasm

      - name: upload smart contracts
        uses: actions/upload-artifact@v4
        with:
          name: smart-contracts
          path: smart-contracts.tar.gz

  test_contracts:
    name: test-contracts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - build_contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup ubuntu
        run: |
          sudo apt-get -y install wabt

      - name: cache setup tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
            ~/.cargo/bin/cargo-audit
          key: setup-tools-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', 'smart_contracts/rust-toolchain', 'Makefile') }}
          restore-keys: |
            setup-tools-${{ runner.os }}-

      - name: setup
        run: make setup

      - uses: Swatinem/rust-cache@v2

      - name: download smart contracts
        uses: actions/download-artifact@v4
        with:
          name: smart-contracts
          path: .

      - name: extract smart contracts
        run: tar -xzf smart-contracts.tar.gz

      - name: test-contracts
        run: make test-contracts-rs CARGO_FLAGS=--release CARGO_TEST_PROFILE_ENV='CARGO_PROFILE_RELEASE_LTO=false CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16'

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs:
      - checks
      - build_contracts
      - test
      - test_contracts
    if: ${{ always() }}
    steps:
      - name: check required jobs
        run: |
          test "${{ needs.checks.result }}" = "success"
          test "${{ needs.build_contracts.result }}" = "success"
          test "${{ needs.test.result }}" = "success"
          test "${{ needs.test_contracts.result }}" = "success"
