---
name: trigger-devnet-upgrade
permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
jobs:
  push_dev_net_protocol_upgrade_if_needed:
    runs-on: ubuntu-latest

    steps:
      # Get script without checkout for use on any repo
      - name: Get script
        run: |
          curl -JLO https://raw.githubusercontent.com/casper-network/casper-node/refs/heads/dev/ci/dev_net_protocol_generate.sh
          chmod +x dev_net_protocol_generate.sh

      # Assign AWS PROD role to get access to production cloudfronts and S3 buckets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_ROLE_GENESIS }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_ACCESS_REGION_GENESIS }}

      - name: Build protocol update
        run: ./dev_net_protocol_generate.sh

      - name: Upload artifacts to S3
        run: aws s3 sync ./target/genesis/ s3://${{ secrets.AWS_BUCKET_GENESIS }}/dev-net/

      # Required in case of overwrite
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_GENESIS }} --paths "/dev-net/*"


