[package]
name = "activate-bid"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2021"

[[bin]]
name = "activate_bid"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
